### ISSUE TITLE
Better git workflow with hooks and tools

### ISSUE THREAD

**Issue by TxHawks** [Haaretz/htz-frontend#10]
We should enforce git guidelines with repository hooks using [Husky](https://github.com/typicode/husky).

Hooks to concider ([prior art](https://github.com/Haaretz/HTZ-HEB/tree/master/.githooks)):
* **post-checkout:** Most branches should be derived off of `master`. Warn when creating a branch derived from any other branch other than master and suggest to re-create it as a child of master.
* **post-checkout and post-commit:** run `lerna bootstrap` when changes to automatically upgrade dependencies whenever a `package.json` file is changed by another developer in any of the packages.
*  **pre-commit:**
   - Format committed files with Prettier
   - Lint committed files
   - Prevent from commiting directly to `master` (can always be bypassed with the `-n` flag)
   - Warn when trying to commit files with unresolved merge conflicts
* **commit-msg:** @tomerbanin, @eliagrady, what do you think of adopting [conventional-changelog](https://github.com/conventional-changelog) or a similar convrntion? If you like it, we can add [this hook](https://github.com/conventional-changelog/validate-commit-msg/blob/master/README.md) or write a similar one to validate commit messages. If we go for it, we should also concider using [Commitizen](https://github.com/commitizen/cz-cli), which can also be [integrated with Jira](https://github.com/CraigGardener/cz-conventional-jira-smart-commit).
* **pre-push:** Prevent deleting or force pushing to long-lived branches

What do you think of using [semntic-release](https://github.com/atlassian/lerna-semantic-release). It requires some discipline with commit messages, but we can enforce that with a `commit-msg` hook and possibly Commitizen.

If we go for conventional-changelog and Commitizen, which I'm totally in favor of, I'll write an Commitizen adaptor that combines [cz-conventiona-jira-smart-commit](https://github.com/CraigGardener/cz-conventional-jira-smart-commit) and [cz-lerna-changelog](https://github.com/atlassian/cz-lerna-changelog)

**Comment by eliagrady** [comment]
In either case we need to have well documented, common workflow scenarios and how to tackle them:

1. Simple case: you're on master (updated or not, shouldn't matter) and you create a feature branch. You commit local changes and push. Finally, you create a pull request.

2. Simple case 2: you're working on a feature, and you need to work on another feature. You stop, add conflicting untracked files to staging, stash (?) go back to master and create a feature branch (continue like case 1). You go back to the old branch, and stash pop to continue working on the original feature.

3. ... //TODO <Add more scenarios>

If we want people to use commitizen, for example, we need to show exactly how it should be used in each of the common scenarios.

As for using a convention to commit messages: sure - we can adopt something similar to conventional release, maybe something like:
[JIRA-task]?:(fix\feat\major)(scope?):<description>

In regards to tooling, let's keep it as simple as possible: I like warnings, not reformatting the code as a hook. If I commit something, I want to know if it's badly formatted, not commit a different version from what I originally wrote. I have this linting and styling hooks as part of the DFP package, so in order to commit, one must pass the linter in full - I think that's good enough - also, you get to learn from the warning messages about the code style.

**Comment by TxHawks** [comment]
Agreed re warnings on commit messages vs automatically rewriting them. Though automatically fixing _some_ linting errors is favorable in my opinion.

Commitizen is not workflow related. It simply asks you questions and builds a commit message for you based on your answers.

It's best to keep message headlines short, so I'd put the Jira ticket at the footer of the message like all Commitizen Jira plugins do.
I suggest:
```git
type(scope/package):message

Optional body

Optional footer that includes Jira tickets, related GitHub issues
```

Regarding workflows, git and otherwise, this is really a seperator subject that should be discussed  a in it's own issue, but no doubt workflows should be well documented, and there should be an easy entry point for new developers and experienced developers alike. We can use the wiki feature in GitHub to do that in a way that obviously ties it to the repository.
