### ISSUE TITLE
Handling common cross-dependencies

### ISSUE THREAD

**Issue by TxHawks** [Haaretz/htz-frontend#7]
I've just had an idea, that's probably too naive to work:
What if we include a list up common dependencies, at the `dependencies` field of the root `package.json`, and have a script to install and a script to update these dependencies either as `peerDependencies` and `devDependencies` for consumable packages, or `dependencies` for application packages

This approach is so simple, that I'm sure it has some shortcomings I am not thinking about, because I haven't seen anyone using or suggesting it in the many discussions about this topic.

**Comment by exogen** [comment]
That sounds like a fine idea, as long as those deps do actually appear in the individual packages' `package.json` (instead of them implicitly falling back to the root `node_modules`). We could even write it in terms of `lerna exec --scope 'some/apps/glob' yarn ...` commands.

Would there be a scenario where a particular app isn't ready to upgrade – in that case, would you just run the command by undo/deselect the changes for that app? In my experience, if there are multiple teams working on apps separately, it's common for some teams to take longer migrating to the latest stack.

I'd recommend not putting them in the actual `dependencies` field of the root `package.json` though, since there's no reason for that package to ever install them itself. I'd make either a custom field in `package.json` or use a separate JSON file. Maybe something like:

```js
"syncDependencies": {
  "app": {
    "dependencies": { ... },
    "devDependencies": { ... }
  },
  "module": {
    "dependencies": { ... },
    "devDependencies": { ... },
    "peerDependencies": { ... }
  }
}
```

**Comment by exogen** [comment]
Somewhat related: https://www.npmjs.com/package/lerna-semver-sync

Open Lerna issue: https://github.com/lerna/lerna/issues/259

**Comment by TxHawks** [comment]
lerna/lerna#259 seems stale (last comment is 8 months old), and there are a few pull requests on this that face resistance for some reason, but lerna-semver-sync looks like exactly what we need

**Comment by exogen** [comment]
It's pretty close, although it doesn't treat any particular package as the source of truth, which would be nice.

**Comment by exogen** [comment]
Here's an experiment, the simplest thing that could work that does this: https://github.com/Haaretz/htz-frontend/commit/4fadb0924692d1866c7bc7c115bb1586a2a521e3

That way you specify the desired deps centrally in the root `package.json`.

**Comment by exogen** [comment]
[ ] Merge script into `master` as a placeholder solution. [ETA 29.08.2017]
